services:
  app:
    build: C:\Users\admin\Desktop\hair_eshop\backend
    image: hair_eshop_backend
    container_name: laravel_app
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:80"
    command: php artisan serve --host=0.0.0.0 --port=80
    depends_on:
      - db

  db:
    image: mariadb:11
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hair_eshop
      MYSQL_USER: hair_user
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  frontend:
    build: C:\Users\admin\Desktop\hair_eshop\frontend
    image: hair_eshop_frontend
    container_name: react_app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db           # názov MariaDB služby
      PMA_USER: hair_user    # voliteľné, môžeš použiť hociktorý DB user
      PMA_PASSWORD: secret   # heslo DB usera
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
